# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MCUProg.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MCUProg(object):
    def setupUi(self, MCUProg):
        MCUProg.setObjectName(_fromUtf8("MCUProg"))
        MCUProg.resize(600, 160)
        self.vLayout = QtGui.QVBoxLayout(MCUProg)
        self.vLayout.setSpacing(12)
        self.vLayout.setObjectName(_fromUtf8("vLayout"))
        self.hLayout1 = QtGui.QHBoxLayout()
        self.hLayout1.setObjectName(_fromUtf8("hLayout1"))
        self.lblMCU = QtGui.QLabel(MCUProg)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblMCU.sizePolicy().hasHeightForWidth())
        self.lblMCU.setSizePolicy(sizePolicy)
        self.lblMCU.setObjectName(_fromUtf8("lblMCU"))
        self.hLayout1.addWidget(self.lblMCU)
        self.cmbMCU = QtGui.QComboBox(MCUProg)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbMCU.sizePolicy().hasHeightForWidth())
        self.cmbMCU.setSizePolicy(sizePolicy)
        self.cmbMCU.setMinimumSize(QtCore.QSize(150, 0))
        self.cmbMCU.setObjectName(_fromUtf8("cmbMCU"))
        self.hLayout1.addWidget(self.cmbMCU)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.hLayout1.addItem(spacerItem)
        self.lblAddr = QtGui.QLabel(MCUProg)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblAddr.sizePolicy().hasHeightForWidth())
        self.lblAddr.setSizePolicy(sizePolicy)
        self.lblAddr.setObjectName(_fromUtf8("lblAddr"))
        self.hLayout1.addWidget(self.lblAddr)
        self.cmbAddr = QtGui.QComboBox(MCUProg)
        self.cmbAddr.setMinimumSize(QtCore.QSize(75, 0))
        self.cmbAddr.setObjectName(_fromUtf8("cmbAddr"))
        self.hLayout1.addWidget(self.cmbAddr)
        self.lblSize = QtGui.QLabel(MCUProg)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblSize.sizePolicy().hasHeightForWidth())
        self.lblSize.setSizePolicy(sizePolicy)
        self.lblSize.setObjectName(_fromUtf8("lblSize"))
        self.hLayout1.addWidget(self.lblSize)
        self.cmbSize = QtGui.QComboBox(MCUProg)
        self.cmbSize.setMinimumSize(QtCore.QSize(75, 0))
        self.cmbSize.setObjectName(_fromUtf8("cmbSize"))
        self.hLayout1.addWidget(self.cmbSize)
        spacerItem1 = QtGui.QSpacerItem(62, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.hLayout1.addItem(spacerItem1)
        self.vLayout.addLayout(self.hLayout1)
        self.hLayout2 = QtGui.QHBoxLayout()
        self.hLayout2.setObjectName(_fromUtf8("hLayout2"))
        self.lblDAP = QtGui.QLabel(MCUProg)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblDAP.sizePolicy().hasHeightForWidth())
        self.lblDAP.setSizePolicy(sizePolicy)
        self.lblDAP.setObjectName(_fromUtf8("lblDAP"))
        self.hLayout2.addWidget(self.lblDAP)
        self.linDAP = QtGui.QLineEdit(MCUProg)
        self.linDAP.setEnabled(False)
        self.linDAP.setObjectName(_fromUtf8("linDAP"))
        self.hLayout2.addWidget(self.linDAP)
        self.btnDAP = QtGui.QPushButton(MCUProg)
        self.btnDAP.setEnabled(False)
        self.btnDAP.setMaximumSize(QtCore.QSize(50, 16777215))
        self.btnDAP.setObjectName(_fromUtf8("btnDAP"))
        self.hLayout2.addWidget(self.btnDAP)
        self.vLayout.addLayout(self.hLayout2)
        self.hLayout3 = QtGui.QHBoxLayout()
        self.hLayout3.setObjectName(_fromUtf8("hLayout3"))
        self.lblHEX = QtGui.QLabel(MCUProg)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblHEX.sizePolicy().hasHeightForWidth())
        self.lblHEX.setSizePolicy(sizePolicy)
        self.lblHEX.setObjectName(_fromUtf8("lblHEX"))
        self.hLayout3.addWidget(self.lblHEX)
        self.cmbHEX = QtGui.QComboBox(MCUProg)
        self.cmbHEX.setObjectName(_fromUtf8("cmbHEX"))
        self.hLayout3.addWidget(self.cmbHEX)
        self.btnHEX = QtGui.QPushButton(MCUProg)
        self.btnHEX.setMaximumSize(QtCore.QSize(50, 16777215))
        self.btnHEX.setObjectName(_fromUtf8("btnHEX"))
        self.hLayout3.addWidget(self.btnHEX)
        self.vLayout.addLayout(self.hLayout3)
        self.hLayout4 = QtGui.QHBoxLayout()
        self.hLayout4.setContentsMargins(-1, 10, -1, -1)
        self.hLayout4.setObjectName(_fromUtf8("hLayout4"))
        self.prgInfo = QtGui.QProgressBar(MCUProg)
        self.prgInfo.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(60)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.prgInfo.sizePolicy().hasHeightForWidth())
        self.prgInfo.setSizePolicy(sizePolicy)
        self.prgInfo.setMaximum(0)
        self.prgInfo.setProperty("value", 0)
        self.prgInfo.setObjectName(_fromUtf8("prgInfo"))
        self.hLayout4.addWidget(self.prgInfo)
        spacerItem2 = QtGui.QSpacerItem(60, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.hLayout4.addItem(spacerItem2)
        self.btnErase = QtGui.QPushButton(MCUProg)
        self.btnErase.setObjectName(_fromUtf8("btnErase"))
        self.hLayout4.addWidget(self.btnErase)
        self.btnWrite = QtGui.QPushButton(MCUProg)
        self.btnWrite.setObjectName(_fromUtf8("btnWrite"))
        self.hLayout4.addWidget(self.btnWrite)
        self.btnRead = QtGui.QPushButton(MCUProg)
        self.btnRead.setObjectName(_fromUtf8("btnRead"))
        self.hLayout4.addWidget(self.btnRead)
        self.vLayout.addLayout(self.hLayout4)

        self.retranslateUi(MCUProg)
        QtCore.QMetaObject.connectSlotsByName(MCUProg)

    def retranslateUi(self, MCUProg):
        MCUProg.setWindowTitle(_translate("MCUProg", "XIVN1987 单片机编程器", None))
        self.lblMCU.setText(_translate("MCUProg", "MCU ：", None))
        self.lblAddr.setText(_translate("MCUProg", "起始：", None))
        self.lblSize.setText(_translate("MCUProg", "大小：", None))
        self.lblDAP.setText(_translate("MCUProg", "DAP ：", None))
        self.btnDAP.setText(_translate("MCUProg", "...", None))
        self.lblHEX.setText(_translate("MCUProg", "文件：", None))
        self.btnHEX.setText(_translate("MCUProg", "...", None))
        self.btnErase.setText(_translate("MCUProg", "擦除", None))
        self.btnWrite.setText(_translate("MCUProg", "擦写", None))
        self.btnRead.setText(_translate("MCUProg", "读取", None))

